services:
    ahs_adverts_plugin.lifecyclesubscriber:
        class: AHS\AdvertsPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
            - @newscoop.plugins.service
        tags:
            - { name: kernel.event_subscriber}

    ahs_adverts_plugin.configure_menu_listener:
        class: AHS\AdvertsPluginBundle\EventListener\ConfigureMenuListener
        tags:
          - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments:
            - @translator

    ahs_adverts_plugin.list_objects.listener:
        class: AHS\AdvertsPluginBundle\EventListener\ListObjectsListener
        tags:
          - { name: kernel.event_listener, event: newscoop.listobjects.register, method: registerObjects }

    ahs_adverts_plugin.permissions.listener:
        class: AHS\AdvertsPluginBundle\EventListener\PermissionsListener
        arguments:
            - @translator
        tags:
          - { name: kernel.event_listener, event: newscoop.plugins.permissions.register, method: registerPermissions }

    ahs_adverts_plugin.serializer.announcement_url_handler:
        class: AHS\AdvertsPluginBundle\Serializer\AnnouncementUrlHandler
        arguments:  [ "@router"]
        tags:
            - { name: jms_serializer.handler, type: announcement_url, direction: serialization, format:json, method:serializeToJson }

    ahs_adverts_plugin.ads_service:
        class: AHS\AdvertsPluginBundle\Service\AnnouncementsService
        arguments:
            - @em
            - @email
            - @newscoop.templates.service
            - @newscoop.placeholders.service
            - @system_preferences_service
            - @router